Blog/Models/BlogAuthor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TheatreCMS3.Areas.Blog.Models
{
    public class BlogAuthor
    {
        public int BlogAuthorId { get; set; }
        public string Name { get; set; }
        public string Bio { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-ddThh:mm}")]
        public DateTime Joined { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-ddThh:mm}")]
        public DateTime? Left { get; set; }
    }
}

Blog/Controllers/BlogAuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TheatreCMS3.Areas.Blog.Models;
using TheatreCMS3.Models;

namespace TheatreCMS3.Areas.Blog.Controllers
{
    public class BlogAuthorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Blog/BlogAuthors
        public ActionResult Index()
        {
            var foo = db.BlogAuthors.ToList();
            return View(foo);
        }

        // GET: Blog/BlogAuthors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogAuthor blogAuthor = db.BlogAuthors.Find(id);
            if (blogAuthor == null)
            {
                return HttpNotFound();
            }
            return View(blogAuthor);
        }

        // GET: Blog/BlogAuthors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Blog/BlogAuthors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BlogAuthorId,Name,Bio,Joined,Left")] BlogAuthor blogAuthor)
        {
            if (ModelState.IsValid)
            {
                db.BlogAuthors.Add(blogAuthor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogAuthor);
        }

        // GET: Blog/BlogAuthors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogAuthor blogAuthor = db.BlogAuthors.Find(id);
            if (blogAuthor == null)
            {
                return HttpNotFound();
            }
            return View(blogAuthor);
        }

        // POST: Blog/BlogAuthors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BlogAuthorId,Name,Bio,Joined,Left")] BlogAuthor blogAuthor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blogAuthor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blogAuthor);
        }

        // GET: Blog/BlogAuthors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogAuthor blogAuthor = db.BlogAuthors.Find(id);
            if (blogAuthor == null)
            {
                return HttpNotFound();
            }
            return View(blogAuthor);
        }

        // POST: Blog/BlogAuthors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogAuthor blogAuthor = db.BlogAuthors.Find(id);
            db.BlogAuthors.Remove(blogAuthor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Blog/Views/Shared/_BlogAuthor.cshtml
@model TheatreCMS3.Areas.Blog.Models.BlogAuthor

@{ 
    string authorTabId = $"author-tab-{Model.BlogAuthorId}";
    string blogTabId = $"blog-tab-{Model.BlogAuthorId}";
    string contactTabId = $"contact-tab-{Model.BlogAuthorId}";
    string twitterTabId = $"twitter-tab-{Model.BlogAuthorId}";

    string authorContentId = $"author-content-{Model.BlogAuthorId}";
    string blogContentId = $"blog-content-{Model.BlogAuthorId}";
    string contactContentId = $"contact-content-{Model.BlogAuthorId}";
    string twitterContentId = $"twitter-content-{Model.BlogAuthorId}"; 
}

<div class="AuthorBtnContainer">
    <div class="AuthorBtnPlacement pt-1 justify-content-center">
        <ul class="nav nav-pills justify-content-center" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" id="@authorTabId" href="@($"#{authorContentId}")" data-toggle="pill" role="tab" aria-controls="@authorContentId" aria-selected="true">Author Details</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="@blogTabId" href="@($"#{blogContentId}")" data-toggle="pill" role="tab" aria-controls="@blogContentId" aria-selected="false">Blog Post</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="@contactTabId" href="@($"#{contactContentId}")" data-toggle="pill" role="tab" aria-controls="@contactContentId" aria-selected="false">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="@twitterTabId" href="@($"#{twitterContentId}")" data-toggle="pill" role="tab" aria-controls="@twitterContentId" aria-selected="false">Twitter</a>
            </li>
        </ul>
    </div>
</div>
<!----------------------top buttons------------------->
<div class="border-0 card text-center">
    <div>
        <div class="row m-3">
            <!---------------------Portrait--------------------->
            <div class="col-lg-4">
                <img src="https://via.placeholder.com/250x300.jpeg?text=Author+Portrait" alt="Author Portrait">
            </div>
            <!---------------------End Portrait--------------------->
            <div class="col-lg-8">
                <div class="tab-content" id="@($"tabContent-{Model.BlogAuthorId}-pills")">
                    <div class="AuthorDetails tab-pane active show" id="@authorContentId" role="tabpanel" aria-labelledby="@authorTabId">
                        <h5 class="card-title">
                            @Html.DisplayFor(model => model.Name)

                            <!---------------------------social media icons------------------------------->
                            <span style="float:right">
                                <a href="https://www.facebook.com/"><i class="fab fa-facebook"></i></a>&nbsp;
                                <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
                            </span>
                            <!--------------------------end social media icons------------------------------>
                        </h5>

                        <p class="card-text">@Html.DisplayFor(model => model.Bio)</p>
                        <div class="row">
                            <div class="col">
                                <p><strong>Joined Date</strong></p>
                                <p>@Html.DisplayFor(model => model.Joined)</p>
                            </div>
                            <div class="col">
                                <p><strong>Left Date</strong></p>
                                <p>@Html.DisplayFor(model => model.Left)</p>
                            </div>
                        </div>
                    </div>
                    <div class="AuthorDetails tab-pane" id="@blogContentId" role="tabpanel" aria-labelledby="@blogTabId">
                        <h5 class="card-title">Post</h5>
                        <p class="card-text">
                            Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum
                            Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum
                            Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum
                            Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum
                            Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum
                            Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum
                            Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum
                        </p>
                    </div>
                    <div class="AuthorDetails tab-pane" id="@contactContentId" role="tabpanel" aria-labelledby="@contactTabId">
                        (Implement in future stories)
                    </div>
                    <div class="AuthorDetails tab-pane" id="@twitterContentId" role="tabpanel" aria-labelledby="@twitterTabId">
                        (Implement in future stories)
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    <!-----------------Edit button------------------->
    <div>
        <a href="@Url.Action("Delete", "BlogAuthors", new { id = Model.BlogAuthorId })" class="btn BtnAuthorDelete">
            <i class="fas fa-trash"></i>
        </a>
        <a href="@Url.Action("Edit", "BlogAuthors", new { id = Model.BlogAuthorId })" class="btn BtnAuthorEdit">
            <i class="fas fa-edit"></i>
            <span>
                <strong>Edit</strong>
            </span>
        </a>
    </div>
    <!-----------------End Edit button------------------->

</div>

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@ViewBag.Title - My ASP.NET Application</title>
  @Styles.Render("~/Content/css")
  @Scripts.Render("~/bundles/modernizr")
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
        </ul>
      </div>
    </div>
  </div>

  <div class="container body-content">
    @RenderBody()
    <hr />
    <footer>
      <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
  </div>

  @Scripts.Render("~/bundles/jquery")
  @Scripts.Render("~/bundles/bootstrap")
  @RenderSection("scripts", required: false)
</body>
</html>